### ISSUE TITLE
Invalid Double

### ISSUE THREAD

**Issue by wjbeckett** [dmstocking/couch-tatertot#2]
Still seem to be getting the invalid double bug showing on my install on Couchtatertot. I am using the latest version (1.2.2). I have re-installed but still no go.
Below is the error on screen:

"Error Retrieving Results
ERROR: java.lang.NumberFormatException: Invalid double: "p6643445"

**Comment by dmstocking** [comment]
Curses I thought I fixed that once and for all.

Well if you could save this page as a file and send it to me. (I'm assuming this is on your "wanted" list)

http://your-server:your-port/api/your-api-key/movies.list/?status=active

I will try to figure this out as fast as I can. (I also need to update Statuses)

Are you using the GooglePlay version or GitHub?

**Comment by wjbeckett** [comment]
It's on any screen.
I've found that I can still search for and add movies to the wanted list and they show up on the Web interface.
I've using the GitHub version.

I van't actually get to that page to save if for you. I get this error:
"Wrong API key used" even thought I'm copying/pasting from the CPv2 web ui...

**Comment by dmstocking** [comment]
Sorry Sorry its not "movies.list" its "movie.list" my bad try with that.

**Comment by wjbeckett** [comment]
emailed to you.

**Comment by dmstocking** [comment]
Yah, I the wrong version must be on GitHub. That shouldn't happend and doesn't with GooglePlay version. I must have somehow grabbed the old .apk before the new one was complete I will update this ASAP.

**Comment by wjbeckett** [comment]
ahhh ok.
Thanks heaps!
