### ISSUE TITLE
searching for a title that does not exist (or is not a movie?) results in an error

### ISSUE THREAD

**Issue by broncosaddict** [dmstocking/couch-tatertot#3]
Error Retrieving Results
ERROR: java.lang.illegalStateException: Expected a boolean but was NUMBER at line 1 column 43

btw: also in your whats new you have a typo (should be google play)   -- this is a deal breaker for me :-)

**Comment by dmstocking** [comment]
I'll look into this I probably don't handle empty search results right.

**Comment by dmstocking** [comment]
Hope I fixed this. If it still has problems let me know.

**Comment by broncosaddict** [comment]
Looks great.  Thanks for the quick fix.  Appreciate it.
