### ISSUE TITLE
Feature request/Workflow change

### ISSUE THREAD

**Issue by broncosaddict** [dmstocking/couch-tatertot#4]
Great app(s), so far they have made my life much easier and I've only been using them for a few hours.

I dont know if its possible or how much effort it would be but, I'm finding the search/add flow to be a bit of a bottleneck.

Currently if you type something in like "kung fu panda", you are give a list of matches.
You can then choose one, in which case you are given more info on that particular one and can additionally add it to your list.
If you decide to just go back (top left) it takes you back to the main page.  

Any way to have it go back to the list of matches instead?  
Same for after adding a movie, have it go back to your list of matches.

Its a real pain to have to have to redo the entire search because I either fat fingered my selection or wanted to choose multiple episodes.

Thanks for your consideration!

**Comment by dmstocking** [comment]
Do u not have a back button? The top left is an up button not back. It goes straight back to the home activity of CouchTatertot.

**Comment by broncosaddict** [comment]
Sorry, I'm an idiot. Your 100% correct.
I got so focused on the top left being "back" that I didn't even think
about the normal back button.
It works absolutely fine

Thanks for the quick response!!
