### ISSUE TITLE
Share from within IMBD app chrashes the app

### ISSUE THREAD

**Issue by vledder** [dmstocking/couch-tatertot#7]
If you do a 'share link' action in IMBD app and choose couch-tatertot it chrashes...

**Comment by dmstocking** [comment]
Are you using the Google Play version or Github? Are you using the newest version? What country are you in? Is your IMDB app the newest version? What movie where you trying to add? Did it crash or just display an error?

**Comment by dmstocking** [comment]
Never mind, I found the problem.

**Comment by dmstocking** [comment]
Should be fixed in 1.3.4
